---
- name: 1) Install Apache
  become: yes
  apt: name=apache2 state=present

- name: 2) Install PHP module for Apache
  become: yes
  apt: name=libapache2-mod-php state=present

- name: 3) Install MySQL extension for PHP
  become: yes
  apt: name=php-mysql state=present

- name: 4) Start Apache
  service: name=apache2 state=started enabled=yes

#- name: ) Pass the script
#  become: yes
#  copy: src=index.php dest=/var/www/html/index.php mode=0664

- name: 5) Install latest Wordpress
  become: yes
  unarchive:
    src: https://wordpress.org/wordpress-latest.tar.gz
    dest: "/var/www/html"
    remote_src: yes
    creates: "/var/www/html/wordpress"

- name: 6) pass wordpress.conf file
  become: yes
  copy: src=wordpress.conf dest=/etc/apache2/sites-available/wordpress.conf

- name: 7) pass wp-config.php file
  become: yes
  copy: src=wp-config.php dest=/var/www/html/wordpress/wp-config.php

- name: 8) Enable the site
  shell: "sudo a2ensite wordpress"

- name: 9) Enable URL rewriting
  shell: "sudo a2enmod rewrite"

- name: 10) Restart Apache
  become: yes
  service: name=apache2 state=restarted